### PR TITLE
Completed Testing

### PR DESCRIPTION
**Pull request by JoelCarr619**

### CODE REVIEW

**Review by elysemontano — CHANGES_REQUESTED** [review]
Your test files for Header, Footer, and Home are not asserting anything.  Currently it is just rendering the component, but not expecting any output.

**Comment by JacobR96** [comment]
Yes ma'am we will get that straight

**Comment by JoelCarr619** [comment]
updated but still working on the problem

**Comment by JoelCarr619** [comment]
updated but still working on the problem

**Comment by JoelCarr619** [comment]
The Updates have been made and adjusted.

**Review by elysemontano — CHANGES_REQUESTED** [review]
One last thing on this one.  Right now your home test file is only rendering the component, but not asserting against anything specific on the page.  Please add a test for this as well.

**Review by elysemontano — APPROVED** [review]

**Pull request merged**
